name: Deploy to DEV

on:
  push:
    branches: [main]       # Trigger on pushes to main
  workflow_dispatch:       # Also allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ROLE: "ACCOUNTADMIN"
      SNOWFLAKE_WAREHOUSE: "DEVOPS_WH"
      SNOWFLAKE_DATABASE: "DEVOPS_DB"
      SNOWFLAKE_SCHEMA: "COMMON"

    steps:
      - name: ✅ Checkout repository
        uses: actions/checkout@v4

      - name: Install Snowflake CLI via pip
        run: |
          python -m pip install --upgrade snowflake-cli

      - name: Verify CLI installation
        run: |
          snow --version
          snow connection test \
            --account $SNOWFLAKE_ACCOUNT \
            --user $SNOWFLAKE_USER \
            --password $SNOWFLAKE_PASSWORD

      - name: Deploy SQL to DEV
        run: |
          snow sql \
            --account $SNOWFLAKE_ACCOUNT \
            --user $SNOWFLAKE_USER \
            --password $SNOWFLAKE_PASSWORD \
            --role $SNOWFLAKE_ROLE \
            --warehouse $SNOWFLAKE_WAREHOUSE \
            --database $SNOWFLAKE_DATABASE \
            --schema $SNOWFLAKE_SCHEMA \
            --file sql/deploy-dev.sql
