name: Deploy to Snowflake (DEV)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v1.5
        with:
          cli-version: '3.5.0'

      - name: Run SQL on Snowflake
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWSQL_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWSQL_PWD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWSQL_ROLE }}
          SNOWFLAKE_WAREHOUSE: DEVOPS_WH
          SNOWFLAKE_DATABASE: DEVOPS_DB
          SNOWFLAKE_SCHEMA: COMMON
        run: |
          echo " Running DEV SQL via env vars..."
          snow sql -f sql/deploy-dev.sql
