name: Deploy to DEV

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_CONNECTIONS_DEFAULT_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_CONNECTIONS_DEFAULT_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_CONNECTIONS_DEFAULT_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_CONNECTIONS_DEFAULT_ROLE: "ACCOUNTADMIN"
      SNOWFLAKE_CONNECTIONS_DEFAULT_WAREHOUSE: "DEVOPS_WH"
      SNOWFLAKE_CONNECTIONS_DEFAULT_DATABASE: "DEVOPS_DB"
      SNOWFLAKE_CONNECTIONS_DEFAULT_SCHEMA: "COMMON"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install Snowflake CLI
        uses: Snowflake-Labs/snowflake-cli-action@v1.5
        with:
          cli-version: "latest"
          default-config-file-path: ".snowflake/config.toml" # optional but recommended :contentReference[oaicite:1]{index=1}

      - name: Test connection
        run: |
          snow --version
          snow connection test

      - name: Deploy to DEV
        run: |
          snow sql --file sql/deploy-dev.sql
